from __future__ import annotations

ATS_DISCOVERY_API_TIMEOUT = 8
CAREER_PAGE_SNIPPET_CHARS = 400
JOB_BOARD_SNIPPET_CHARS = 1000
LLM_REPAIR_INPUT_CHARS = 2000
DEFAULT_BATCH_SIZE = 15
MIN_FULL_JD_SNIPPET_CHARS = 300
VALIDATION_SNIPPET_CHARS = 2000
