from __future__ import annotations

from copy import deepcopy
from typing import Any

SECRET_ENV_VARS: dict[str, str] = {
    "anthropic": "ANTHROPIC_API_KEY",
    "openai": "OPENAI_API_KEY",
    "google": "GOOGLE_API_KEY",
    "brave": "BRAVE_API_KEY",
    "tavily": "TAVILY_API_KEY",
    "exa": "EXA_API_KEY",
    "rapidapi": "RAPIDAPI_KEY",
    "jooble": "JOOBLE_API_KEY",
    "adzuna_app_id": "ADZUNA_APP_ID",
    "adzuna_api_key": "ADZUNA_API_KEY",
    "reed": "REED_API_KEY",
}

LLM_ROLE_DEFAULTS: dict[str, Any] = {
    "default_provider": "anthropic",
    "providers": {
        "validation": "anthropic",
        "scoring": "anthropic",
        "tailoring": "anthropic",
        "cover_letter": "anthropic",
        "research": "anthropic",
        "linkedin": "anthropic",
        "jd_extraction": "anthropic",
    },
    "models": {
        "validation": "claude-haiku-4-5-20251001",
        "scoring": "claude-haiku-4-5-20251001",
        "tailoring": "claude-sonnet-4-6",
        "cover_letter": "claude-sonnet-4-6",
        "research": "claude-haiku-4-5-20251001",
        "linkedin": "claude-sonnet-4-6",
        "jd_extraction": "claude-haiku-4-5-20251001",
    },
    "max_tokens": {
        "validation": 200,
        "scoring": 1000,
        "tailoring": 4000,
        "cover_letter": 800,
        "research": 800,
        "linkedin": 6000,
        "jd_extraction": 1500,
    },
    "max_workers": 5,
    "rate_limits": {},
    "ollama": {"base_url": "http://localhost:11434"},
}

JOB_BOARD_SOURCE_NAMES: tuple[str, ...] = (
    "careerjet",
    "workingnomads",
    "jobspy",
    "remotive",
    "the_muse",
    "jobicy",
    "remoteok",
    "weworkremotely",
    "jooble",
    "himalayas",
    "adzuna",
    "reed",
    "mycareersfuture",
    "jobstreet",
    "jobbank",
    "gulftalent",
    "bayt",
    "hh",
    "arbeitsagentur",
    "arbeitnow",
    "jsearch",
)

ATS_DISCOVERY_SOURCES: tuple[str, ...] = (
    "greenhouse",
    "lever",
    "ashby",
    "smartrecruiters",
    "workable",
    "personio",
    "recruitee",
    "hibob",
    "teamtailor",
    "breezy",
    "workday",
    "bamboohr",
)

STALE_INDICATORS: tuple[str, ...] = (
    "no longer available",
    "this job has expired",
    "position has been filled",
    "not accepting applications",
    "applications are closed",
    "job is closed",
    "posting has closed",
)

EXCLUDED_LISTING_URL_PATTERNS: tuple[str, ...] = (
    r"linkedin\.com/jobs/search",
    r"linkedin\.com/jobs/[^/?#]+-jobs",
    r"linkedin\.com/jobs/collections",
    r"linkedin\.com/jobs/remote-",
    r"linkedin\.com/jobs/[a-z]+-stellen",
    r"linkedin\.com/jobs/[a-z]+-stellenangebote",
)

LANGUAGE_INDICATORS: dict[str, tuple[str, ...]] = {
    "german": (
        "wir suchen",
        "wir freuen uns",
        "jetzt bewerben",
        "ihre aufgaben",
        "ihr profil",
        "deine aufgaben",
        "dein profil",
        "was wir bieten",
        "was du mitbringst",
        "das bieten wir",
        "stellenangebot",
        "berufserfahrung",
        "deutschkenntnisse",
    ),
    "italian": (
        "siamo alla ricerca",
        "la tua candidatura",
        "invia candidatura",
        "le tue responsabilita",
        "cosa offriamo",
        "requisiti richiesti",
    ),
    "spanish": (
        "buscamos",
        "envia tu solicitud",
        "tus responsabilidades",
        "tu perfil",
        "que ofrecemos",
        "nuestra compañia",
        "nuestra empresa",
        "nuestro equipo",
        "somos una empresa",
        "fue fundada",
    ),
    "french": (
        "nous recherchons",
        "votre candidature",
        "vos missions",
        "votre profil",
        "ce que nous offrons",
    ),
    "dutch": (
        "wij zoeken",
        "jouw profiel",
        "je verantwoordelijkheden",
        "solliciteer nu",
        "wat wij bieden",
    ),
    "portuguese": (
        "candidatar",
        "requisitos",
        "experiência",
        "vaga",
        "cargo",
        "habilidades",
        "obrigatório",
        "sua candidatura",
        "venha trabalhar",
        "nos estamos procurando",
        "nossa empresa",
        "nossa equipe",
        "somos uma empresa",
        "foi fundada",
    ),
    "russian": (
        "мы ищем",
        "требования",
        "обязанности",
        "опыт работы",
        "заработная плата",
        "условия работы",
        "отправить резюме",
    ),
    "polish": (
        "szukamy",
        "wymagania",
        "obowiązki",
        "aplikuj teraz",
        "doświadczenie",
        "wynagrodzenie",
    ),
    "czech": (
        "hledáme",
        "požadavky",
        "nabízíme",
        "zkušenosti",
        "nástup možný",
    ),
    "slovak": (
        "hľadáme",
        "požiadavky",
        "ponúkame",
        "pracovná náplň",
    ),
    "hungarian": (
        "keresünk",
        "követelmények",
        "feladatok",
        "tapasztalat",
        "amit kínálunk",
    ),
    "romanian": (
        "căutăm",
        "cerințe",
        "responsabilități",
        "experiență",
        "ce oferim",
    ),
    "swedish": (
        "vi söker",
        "arbetsuppgifter",
        "ansök nu",
        "erfarenhet",
        "vi erbjuder",
    ),
    "danish": (
        "vi søger",
        "arbejdsopgaver",
        "ansøg nu",
        "erfaring",
        "vi tilbyder",
    ),
    "norwegian": (
        "vi søker",
        "arbeidsoppgaver",
        "søk nå",
        "vi tilbyr",
    ),
    "finnish": (
        "etsimme",
        "vaatimukset",
        "tehtävät",
        "hae nyt",
        "tarjoamme",
    ),
    "greek": (
        "αναζητούμε",
        "απαιτήσεις",
        "καθήκοντα",
        "εμπειρία",
        "προσφέρουμε",
    ),
    "turkish": (
        "arıyoruz",
        "gereksinimler",
        "görevler",
        "deneyim",
        "sunuyoruz",
    ),
    "arabic": (
        "نحن نبحث",
        "المتطلبات",
        "المهام",
        "قدم الآن",
        "الخبرة",
    ),
    "hebrew": (
        "אנחנו מחפשים",
        "דרישות",
        "ניסיון",
        "שלח קורות חיים",
    ),
    "chinese": (
        "我们在寻找",
        "职位要求",
        "岗位职责",
        "工作经验",
        "薪资待遇",
    ),
    "japanese": (
        "募集要項",
        "業務内容",
        "応募資格",
        "勤務地",
        "給与",
    ),
    "korean": (
        "채용 공고",
        "지원 자격",
        "담당 업무",
        "경력",
        "급여",
    ),
    "hindi": (
        "हम खोज रहे हैं",
        "आवश्यकताएं",
        "अनुभव",
        "आवेदन करें",
    ),
    "indonesian": (
        "kami mencari",
        "persyaratan",
        "tanggung jawab",
        "pengalaman",
        "lamar sekarang",
    ),
    "thai": (
        "เรากำลังมองหา",
        "คุณสมบัติ",
        "ประสบการณ์",
        "สมัครงาน",
    ),
    "vietnamese": (
        "chúng tôi tìm kiếm",
        "yêu cầu",
        "kinh nghiệm",
        "ứng tuyển ngay",
    ),
    "ukrainian": (
        "ми шукаємо",
        "вимоги",
        "обов'язки",
        "досвід роботи",
    ),
    "catalan": (
        "busquem",
        "requisits",
        "responsabilitats",
        "experiència",
    ),
}

# Maps country names/aliases → ISO 3166-1 alpha-2 codes for location restriction detection.
# Longer names must be checked before shorter ones to avoid partial matches (handled by caller).
_COUNTRY_NAME_TO_CODE: dict[str, str] = {
    # North America
    "united states of america": "US",
    "united states": "US",
    "u.s.a.": "US",
    "u.s.": "US",
    "usa": "US",
    "america": "US",
    "canada": "CA",
    "mexico": "MX",
    "méxico": "MX",
    # South / Central America
    "brazil": "BR",
    "brasil": "BR",
    "argentina": "AR",
    "colombia": "CO",
    "chile": "CL",
    "peru": "PE",
    "venezuela": "VE",
    "ecuador": "EC",
    "bolivia": "BO",
    "uruguay": "UY",
    "paraguay": "PY",
    "costa rica": "CR",
    "panama": "PA",
    "guatemala": "GT",
    # Europe
    "united kingdom": "GB",
    "great britain": "GB",
    "britain": "GB",
    "england": "GB",
    "u.k.": "GB",
    "germany": "DE",
    "deutschland": "DE",
    "france": "FR",
    "spain": "ES",
    "italy": "IT",
    "netherlands": "NL",
    "holland": "NL",
    "belgium": "BE",
    "switzerland": "CH",
    "austria": "AT",
    "sweden": "SE",
    "norway": "NO",
    "denmark": "DK",
    "finland": "FI",
    "poland": "PL",
    "czech republic": "CZ",
    "czechia": "CZ",
    "slovakia": "SK",
    "hungary": "HU",
    "romania": "RO",
    "bulgaria": "BG",
    "croatia": "HR",
    "serbia": "RS",
    "ukraine": "UA",
    "portugal": "PT",
    "greece": "GR",
    "ireland": "IE",
    "luxembourg": "LU",
    "estonia": "EE",
    "latvia": "LV",
    "lithuania": "LT",
    "slovenia": "SI",
    "iceland": "IS",
    "malta": "MT",
    "cyprus": "CY",
    "albania": "AL",
    "north macedonia": "MK",
    "bosnia": "BA",
    "moldova": "MD",
    "belarus": "BY",
    # Middle East
    "israel": "IL",
    "united arab emirates": "AE",
    "u.a.e.": "AE",
    "uae": "AE",
    "saudi arabia": "SA",
    "türkiye": "TR",
    "turkey": "TR",
    "iran": "IR",
    "iraq": "IQ",
    "jordan": "JO",
    "egypt": "EG",
    "qatar": "QA",
    "kuwait": "KW",
    "bahrain": "BH",
    "oman": "OM",
    "lebanon": "LB",
    "syria": "SY",
    "yemen": "YE",
    # Asia-Pacific
    "india": "IN",
    "china": "CN",
    "japan": "JP",
    "south korea": "KR",
    "korea": "KR",
    "singapore": "SG",
    "philippines": "PH",
    "indonesia": "ID",
    "thailand": "TH",
    "vietnam": "VN",
    "malaysia": "MY",
    "pakistan": "PK",
    "bangladesh": "BD",
    "sri lanka": "LK",
    "nepal": "NP",
    "myanmar": "MM",
    "cambodia": "KH",
    "taiwan": "TW",
    "hong kong": "HK",
    "australia": "AU",
    "new zealand": "NZ",
    "afghanistan": "AF",
    "kazakhstan": "KZ",
    # Africa
    "south africa": "ZA",
    "nigeria": "NG",
    "kenya": "KE",
    "ghana": "GH",
    "ethiopia": "ET",
    "morocco": "MA",
    "tanzania": "TZ",
    "uganda": "UG",
    "senegal": "SN",
    "ivory coast": "CI",
    "côte d'ivoire": "CI",
    "cameroon": "CM",
    "zimbabwe": "ZW",
    "zambia": "ZM",
    "rwanda": "RW",
    # Cities — ordered longest-first within country to avoid partial matches
    # Germany
    "frankfurt am main": "DE",
    "frankfurt": "DE",
    "munich": "DE",
    "münchen": "DE",
    "muenchen": "DE",
    "berlin": "DE",
    "hamburg": "DE",
    "cologne": "DE",
    "köln": "DE",
    "koeln": "DE",
    "stuttgart": "DE",
    "düsseldorf": "DE",
    "duesseldorf": "DE",
    "leipzig": "DE",
    "nuremberg": "DE",
    "nürnberg": "DE",
    "nuernberg": "DE",
    "hannover": "DE",
    "dresden": "DE",
    "dortmund": "DE",
    "essen": "DE",
    "bremen": "DE",
    # United Kingdom
    "london": "GB",
    "manchester": "GB",
    "birmingham": "GB",
    "edinburgh": "GB",
    "glasgow": "GB",
    "bristol": "GB",
    "leeds": "GB",
    "sheffield": "GB",
    "liverpool": "GB",
    "cambridge": "GB",
    "oxford": "GB",
    # France
    "paris": "FR",
    "lyon": "FR",
    "marseille": "FR",
    "toulouse": "FR",
    "bordeaux": "FR",
    "nice": "FR",
    "nantes": "FR",
    "strasbourg": "FR",
    "lille": "FR",
    # Netherlands
    "amsterdam": "NL",
    "rotterdam": "NL",
    "eindhoven": "NL",
    "utrecht": "NL",
    "den haag": "NL",
    "the hague": "NL",
    "groningen": "NL",
    # Spain
    "madrid": "ES",
    "barcelona": "ES",
    "seville": "ES",
    "sevilla": "ES",
    "valencia": "ES",
    "bilbao": "ES",
    "málaga": "ES",
    "malaga": "ES",
    # Italy
    "milan": "IT",
    "milano": "IT",
    "rome": "IT",
    "roma": "IT",
    "turin": "IT",
    "torino": "IT",
    "naples": "IT",
    "napoli": "IT",
    "florence": "IT",
    "firenze": "IT",
    "bologna": "IT",
    # Switzerland
    "zurich": "CH",
    "zürich": "CH",
    "zuerich": "CH",
    "geneva": "CH",
    "genève": "CH",
    "geneve": "CH",
    "bern": "CH",
    "basel": "CH",
    "lausanne": "CH",
    # Austria
    "vienna": "AT",
    "wien": "AT",
    "graz": "AT",
    "linz": "AT",
    "salzburg": "AT",
    "innsbruck": "AT",
    # Sweden
    "stockholm": "SE",
    "gothenburg": "SE",
    "göteborg": "SE",
    "goteborg": "SE",
    "malmö": "SE",
    "malmo": "SE",
    # Norway
    "oslo": "NO",
    "bergen": "NO",
    "trondheim": "NO",
    # Denmark
    "copenhagen": "DK",
    "københavn": "DK",
    "kobenhavn": "DK",
    "aarhus": "DK",
    # Finland
    "helsinki": "FI",
    "tampere": "FI",
    "turku": "FI",
    # Poland
    "warsaw": "PL",
    "warszawa": "PL",
    "krakow": "PL",
    "kraków": "PL",
    "krakau": "PL",
    "wroclaw": "PL",
    "wrocław": "PL",
    "gdansk": "PL",
    "gdańsk": "PL",
    "poznan": "PL",
    "poznań": "PL",
    # Czech Republic
    "prague": "CZ",
    "praha": "CZ",
    "brno": "CZ",
    # Hungary
    "budapest": "HU",
    # Portugal
    "lisbon": "PT",
    "lisboa": "PT",
    "porto": "PT",
    # Ireland
    "dublin": "IE",
    "cork": "IE",
    # Belgium
    "brussels": "BE",
    "bruxelles": "BE",
    "brussel": "BE",
    "antwerp": "BE",
    "antwerpen": "BE",
    "ghent": "BE",
    "gent": "BE",
    "liège": "BE",
    # Luxembourg
    "luxembourg city": "LU",
    # Romania
    "bucharest": "RO",
    "bucurești": "RO",
    "cluj": "RO",
    # Ukraine
    "kyiv": "UA",
    "kharkiv": "UA",
    "lviv": "UA",
    # Israel
    "tel aviv": "IL",
    "jerusalem": "IL",
    "haifa": "IL",
    # UAE
    "dubai": "AE",
    "abu dhabi": "AE",
    # United States — long names first
    "new york city": "US",
    "new york": "US",
    "san francisco": "US",
    "los angeles": "US",
    "washington dc": "US",
    "washington d.c.": "US",
    "seattle": "US",
    "boston": "US",
    "chicago": "US",
    "austin": "US",
    "denver": "US",
    "atlanta": "US",
    "miami": "US",
    "portland": "US",
    "dallas": "US",
    "houston": "US",
    "san jose": "US",
    "san diego": "US",
    "phoenix": "US",
    "minneapolis": "US",
    "detroit": "US",
    "philadelphia": "US",
    "pittsburgh": "US",
    "charlotte": "US",
    "raleigh": "US",
    # Canada
    "toronto": "CA",
    "montreal": "CA",
    "montréal": "CA",
    "vancouver": "CA",
    "calgary": "CA",
    "ottawa": "CA",
    "edmonton": "CA",
    "winnipeg": "CA",
    # Australia
    "sydney": "AU",
    "melbourne": "AU",
    "brisbane": "AU",
    "perth": "AU",
    "canberra": "AU",
    "adelaide": "AU",
    # New Zealand
    "auckland": "NZ",
    "wellington": "NZ",
    "christchurch": "NZ",
    # India
    "bangalore": "IN",
    "bengaluru": "IN",
    "mumbai": "IN",
    "bombay": "IN",
    "new delhi": "IN",
    "hyderabad": "IN",
    "pune": "IN",
    "chennai": "IN",
    "kolkata": "IN",
    "ahmedabad": "IN",
    "noida": "IN",
    "gurgaon": "IN",
    "gurugram": "IN",
    # Japan
    "tokyo": "JP",
    "osaka": "JP",
    "kyoto": "JP",
    "yokohama": "JP",
    "nagoya": "JP",
    # South Korea
    "seoul": "KR",
    "busan": "KR",
    # Brazil
    "são paulo": "BR",
    "sao paulo": "BR",
    "rio de janeiro": "BR",
    "brasília": "BR",
    "brasilia": "BR",
    "belo horizonte": "BR",
    # South Africa
    "johannesburg": "ZA",
    "cape town": "ZA",
    "durban": "ZA",
    "pretoria": "ZA",
    # Kenya
    "nairobi": "KE",
}

# Phrase templates for detecting country-specific work restrictions in JD text.
# Caller formats each with a country name before checking.
_RESTRICTION_PHRASES: tuple[str, ...] = (
    "{} only",
    "{}-only",
    "only {}",
    "{}-based candidates only",
    "must be based in {}",
    "must be located in {}",
    "must reside in {}",
    "must live in {}",
    "authorized to work in {}",
    "authorized to work in the {}",
    "work authorization in {}",
    "work authorization required in {}",
    "candidates in {} only",
    "candidates from {} only",
    "applicants from {} only",
    "open to {} candidates only",
    "open to candidates in {}",
    "based in {} required",
    "relocation to {} required",
    "remote/{}",
    "remote - {}",
    "remote – {}",
    "remote in {}",
    "{} remote",
    "({}) remote",
    "(remote/{}) ",
)

# US/Canada shorthand patterns too ambiguous for the country-name loop ("us" is a pronoun).
# Checked directly in is_location_restricted when US is not an allowed region.
_US_ONLY_PHRASES: frozenset[str] = frozenset(
    {
        "us remote",
        "us-remote",
        "remote - united states",
        "remote – united states",
        "(us remote)",
        "us/can remote",
        "us/ca remote",
        "remote within the us",
        "within the united states",
        "canada or mexico",
        "mexico or canada",
        "remote (us only)",
    }
)

SCORING_PROMPT_CONTEXT: dict[str, Any] = {
    "resume_mode": "compact_text",
    "resume_max_chars": 4500,
    "job_description_max_chars": 5000,
    "max_matched_keywords": 10,
    "max_gaps": 5,
}

TAILORING_DEFAULTS: dict[str, Any] = {
    "stories": {"max_chars_for_tailoring": 16000},
    "keyword_strategy": {"aggressiveness": "natural", "avoid_keywords": []},
    "rules": {
        "forbidden_modifications": [],
        "allowed_modifications": ["summary", "bullets", "skills", "active_projects"],
        "preserve_latex": True,
        "summary": {"max_lines": 4, "no_em_dashes": True, "proof_point_preferences": []},
        "bullets": {"max_per_role": 5},
        "projects": {
            "max_projects": 4,
            "min_bullets_per_project": 3,
            "max_bullets_per_project": 5,
            "max_total_resume_pages": 2,
        },
    },
}

COVER_LETTER_DEFAULTS: dict[str, Any] = {
    "tone": ["formal", "confident", "substantive"],
    "header": {
        "include_date": True,
        "date_format": "%B %d, %Y",
        "salutation": "Dear Hiring Manager,",
    },
    "closing": {"format": "Best regards\nCandidate Name"},
    "content": {"target_words": 220, "max_words": 280, "paragraphs": 4},
    "forbidden": {"style": [], "phrases": []},
    "stories": {"max_chars_for_cover": 6000},
    "structure": {
        "paragraph_1": {
            "name": "Opening",
            "max_sentences": 3,
            "purpose": "Connect the role, company, and candidate positioning.",
        },
        "paragraph_2": {
            "name": "Evidence",
            "max_sentences": 4,
            "purpose": "Use verified story-bank proof relevant to the job.",
        },
        "paragraph_3": {
            "name": "Fit",
            "max_sentences": 4,
            "purpose": "Explain how the candidate would help with the role's priorities.",
        },
        "paragraph_4": {
            "name": "Close",
            "max_sentences": 2,
            "purpose": "End with concise interest and availability for next steps.",
        },
    },
}

LINKEDIN_DEFAULTS: dict[str, Any] = {
    "enabled": False,
    "positioning": "",
    "audience": [],
    "content_pillars": [],
    "target_companies": [],
    "tone": [],
    "forbidden_phrases": [],
    "confidentiality": {"forbidden_public_details": []},
    "files": {
        "ideas": "outputs/linkedin/ideas.md",
        "drafts_dir": "outputs/linkedin/drafts",
        "networking": "outputs/linkedin/networking.md",
    },
    "idea_generation": {"ideas_per_run": 3},
    "draft_generation": {
        "posts_per_run": 1,
        "source_status": "raw",
        "mark_converted": True,
        "max_words_per_post": 150,
    },
    "networking_discovery": {
        "results_per_query": 5,
        "region": {"country": "", "search_lang": "en", "location": ""},
    },
    "networking": {"max_message_words": 70},
}

HTTP_DEFAULTS: dict[str, Any] = {
    "url_verification": {"enabled": True, "timeout_seconds": 5, "max_workers": 5},
    "ats_discovery": {"enabled": True, "timeout_seconds": 10, "sources": list(ATS_DISCOVERY_SOURCES)},
    "ats_scraper": {"timeout_seconds": 10},
    "playwright": {"timeout_seconds": 10},
    "jd_fetcher": {"timeout_seconds": 10},
    "jd_enrichment": {"timeout_seconds": 10, "max_workers": 5, "skip_url_patterns": []},
    "url_liveness": {"timeout_seconds": 10, "max_consecutive_failures": 3},
    "search_providers": {
        "timeout_seconds": 10,
        "max_consecutive_failures": 3,
        "order": ["searxng", "brave"],
        "ats_discovery_order": ["searxng", "brave", "exa"],
        "searxng_base_url": "",
        "ats_discovery": {"enabled": True, "sources": list(ATS_DISCOVERY_SOURCES)},
    },
    "job_boards": {
        "timeout_seconds": 10,
        "max_consecutive_failures": 3,
        **{name: {"enabled": True} for name in JOB_BOARD_SOURCE_NAMES},
        "careerjet": {"enabled": True, "affid": ""},
        "jobspy": {"enabled": True, "hours_old": 72},
    },
    "api_budgets": {
        "enabled": True,
        "state_path": "outputs/state/api_usage.json",
        "monthly_limits": {},
    },
}


def deep_merge(base: dict[str, Any], override: dict[str, Any]) -> dict[str, Any]:
    merged = deepcopy(base)
    for key, value in override.items():
        if isinstance(value, dict) and isinstance(merged.get(key), dict):
            merged[key] = deep_merge(merged[key], value)
        else:
            merged[key] = deepcopy(value)
    return merged
