"""Location data: country/city name lookups and restriction-phrase detection."""

from __future__ import annotations

# Maps country names/aliases → ISO 3166-1 alpha-2 codes for location restriction detection.
# Longer names must be checked before shorter ones to avoid partial matches (handled by caller).
COUNTRY_NAME_TO_CODE: dict[str, str] = {
    # North America
    "united states of america": "US",
    "united states": "US",
    "u.s.a.": "US",
    "u.s.": "US",
    "usa": "US",
    "america": "US",
    "canada": "CA",
    "mexico": "MX",
    "méxico": "MX",
    # South / Central America
    "brazil": "BR",
    "brasil": "BR",
    "argentina": "AR",
    "colombia": "CO",
    "chile": "CL",
    "peru": "PE",
    "venezuela": "VE",
    "ecuador": "EC",
    "bolivia": "BO",
    "uruguay": "UY",
    "paraguay": "PY",
    "costa rica": "CR",
    "panama": "PA",
    "guatemala": "GT",
    # Europe
    "united kingdom": "GB",
    "great britain": "GB",
    "britain": "GB",
    "england": "GB",
    "u.k.": "GB",
    "germany": "DE",
    "deutschland": "DE",
    "france": "FR",
    "spain": "ES",
    "italy": "IT",
    "netherlands": "NL",
    "holland": "NL",
    "belgium": "BE",
    "switzerland": "CH",
    "austria": "AT",
    "sweden": "SE",
    "norway": "NO",
    "denmark": "DK",
    "finland": "FI",
    "poland": "PL",
    "czech republic": "CZ",
    "czechia": "CZ",
    "slovakia": "SK",
    "hungary": "HU",
    "romania": "RO",
    "bulgaria": "BG",
    "croatia": "HR",
    "serbia": "RS",
    "ukraine": "UA",
    "portugal": "PT",
    "greece": "GR",
    "ireland": "IE",
    "luxembourg": "LU",
    "estonia": "EE",
    "latvia": "LV",
    "lithuania": "LT",
    "slovenia": "SI",
    "iceland": "IS",
    "malta": "MT",
    "cyprus": "CY",
    "albania": "AL",
    "north macedonia": "MK",
    "bosnia": "BA",
    "moldova": "MD",
    "belarus": "BY",
    # Middle East
    "israel": "IL",
    "united arab emirates": "AE",
    "u.a.e.": "AE",
    "uae": "AE",
    "saudi arabia": "SA",
    "türkiye": "TR",
    "turkey": "TR",
    "iran": "IR",
    "iraq": "IQ",
    "jordan": "JO",
    "egypt": "EG",
    "qatar": "QA",
    "kuwait": "KW",
    "bahrain": "BH",
    "oman": "OM",
    "lebanon": "LB",
    "syria": "SY",
    "yemen": "YE",
    # Asia-Pacific
    "india": "IN",
    "china": "CN",
    "japan": "JP",
    "south korea": "KR",
    "korea": "KR",
    "singapore": "SG",
    "philippines": "PH",
    "indonesia": "ID",
    "thailand": "TH",
    "vietnam": "VN",
    "malaysia": "MY",
    "pakistan": "PK",
    "bangladesh": "BD",
    "sri lanka": "LK",
    "nepal": "NP",
    "myanmar": "MM",
    "cambodia": "KH",
    "taiwan": "TW",
    "hong kong": "HK",
    "australia": "AU",
    "new zealand": "NZ",
    "afghanistan": "AF",
    "kazakhstan": "KZ",
    # Africa
    "south africa": "ZA",
    "nigeria": "NG",
    "kenya": "KE",
    "ghana": "GH",
    "ethiopia": "ET",
    "morocco": "MA",
    "tanzania": "TZ",
    "uganda": "UG",
    "senegal": "SN",
    "ivory coast": "CI",
    "côte d'ivoire": "CI",
    "cameroon": "CM",
    "zimbabwe": "ZW",
    "zambia": "ZM",
    "rwanda": "RW",
    # Cities — ordered longest-first within country to avoid partial matches
    # Germany
    "frankfurt am main": "DE",
    "frankfurt": "DE",
    "munich": "DE",
    "münchen": "DE",
    "muenchen": "DE",
    "berlin": "DE",
    "hamburg": "DE",
    "cologne": "DE",
    "köln": "DE",
    "koeln": "DE",
    "stuttgart": "DE",
    "düsseldorf": "DE",
    "duesseldorf": "DE",
    "leipzig": "DE",
    "nuremberg": "DE",
    "nürnberg": "DE",
    "nuernberg": "DE",
    "hannover": "DE",
    "dresden": "DE",
    "dortmund": "DE",
    "essen": "DE",
    "bremen": "DE",
    # United Kingdom
    "london": "GB",
    "manchester": "GB",
    "birmingham": "GB",
    "edinburgh": "GB",
    "glasgow": "GB",
    "bristol": "GB",
    "leeds": "GB",
    "sheffield": "GB",
    "liverpool": "GB",
    "cambridge": "GB",
    "oxford": "GB",
    # France
    "paris": "FR",
    "lyon": "FR",
    "marseille": "FR",
    "toulouse": "FR",
    "bordeaux": "FR",
    "nice": "FR",
    "nantes": "FR",
    "strasbourg": "FR",
    "lille": "FR",
    # Netherlands
    "amsterdam": "NL",
    "rotterdam": "NL",
    "eindhoven": "NL",
    "utrecht": "NL",
    "den haag": "NL",
    "the hague": "NL",
    "groningen": "NL",
    # Spain
    "madrid": "ES",
    "barcelona": "ES",
    "seville": "ES",
    "sevilla": "ES",
    "valencia": "ES",
    "bilbao": "ES",
    "málaga": "ES",
    "malaga": "ES",
    # Italy
    "milan": "IT",
    "milano": "IT",
    "rome": "IT",
    "roma": "IT",
    "turin": "IT",
    "torino": "IT",
    "naples": "IT",
    "napoli": "IT",
    "florence": "IT",
    "firenze": "IT",
    "bologna": "IT",
    # Switzerland
    "zurich": "CH",
    "zürich": "CH",
    "zuerich": "CH",
    "geneva": "CH",
    "genève": "CH",
    "geneve": "CH",
    "bern": "CH",
    "basel": "CH",
    "lausanne": "CH",
    # Austria
    "vienna": "AT",
    "wien": "AT",
    "graz": "AT",
    "linz": "AT",
    "salzburg": "AT",
    "innsbruck": "AT",
    # Sweden
    "stockholm": "SE",
    "gothenburg": "SE",
    "göteborg": "SE",
    "goteborg": "SE",
    "malmö": "SE",
    "malmo": "SE",
    # Norway
    "oslo": "NO",
    "bergen": "NO",
    "trondheim": "NO",
    # Denmark
    "copenhagen": "DK",
    "københavn": "DK",
    "kobenhavn": "DK",
    "aarhus": "DK",
    # Finland
    "helsinki": "FI",
    "tampere": "FI",
    "turku": "FI",
    # Poland
    "warsaw": "PL",
    "warszawa": "PL",
    "krakow": "PL",
    "kraków": "PL",
    "krakau": "PL",
    "wroclaw": "PL",
    "wrocław": "PL",
    "gdansk": "PL",
    "gdańsk": "PL",
    "poznan": "PL",
    "poznań": "PL",
    # Czech Republic
    "prague": "CZ",
    "praha": "CZ",
    "brno": "CZ",
    # Hungary
    "budapest": "HU",
    # Portugal
    "lisbon": "PT",
    "lisboa": "PT",
    "porto": "PT",
    # Ireland
    "dublin": "IE",
    "cork": "IE",
    # Belgium
    "brussels": "BE",
    "bruxelles": "BE",
    "brussel": "BE",
    "antwerp": "BE",
    "antwerpen": "BE",
    "ghent": "BE",
    "gent": "BE",
    "liège": "BE",
    # Luxembourg
    "luxembourg city": "LU",
    # Romania
    "bucharest": "RO",
    "bucurești": "RO",
    "cluj": "RO",
    # Ukraine
    "kyiv": "UA",
    "kharkiv": "UA",
    "lviv": "UA",
    # Israel
    "tel aviv": "IL",
    "jerusalem": "IL",
    "haifa": "IL",
    # UAE
    "dubai": "AE",
    "abu dhabi": "AE",
    # United States — long names first
    "new york city": "US",
    "new york": "US",
    "san francisco": "US",
    "los angeles": "US",
    "washington dc": "US",
    "washington d.c.": "US",
    "seattle": "US",
    "boston": "US",
    "chicago": "US",
    "austin": "US",
    "denver": "US",
    "atlanta": "US",
    "miami": "US",
    "portland": "US",
    "dallas": "US",
    "houston": "US",
    "san jose": "US",
    "san diego": "US",
    "phoenix": "US",
    "minneapolis": "US",
    "detroit": "US",
    "philadelphia": "US",
    "pittsburgh": "US",
    "charlotte": "US",
    "raleigh": "US",
    # Canada
    "toronto": "CA",
    "montreal": "CA",
    "montréal": "CA",
    "vancouver": "CA",
    "calgary": "CA",
    "ottawa": "CA",
    "edmonton": "CA",
    "winnipeg": "CA",
    # Australia
    "sydney": "AU",
    "melbourne": "AU",
    "brisbane": "AU",
    "perth": "AU",
    "canberra": "AU",
    "adelaide": "AU",
    # New Zealand
    "auckland": "NZ",
    "wellington": "NZ",
    "christchurch": "NZ",
    # India
    "bangalore": "IN",
    "bengaluru": "IN",
    "mumbai": "IN",
    "bombay": "IN",
    "new delhi": "IN",
    "hyderabad": "IN",
    "pune": "IN",
    "chennai": "IN",
    "kolkata": "IN",
    "ahmedabad": "IN",
    "noida": "IN",
    "gurgaon": "IN",
    "gurugram": "IN",
    # Japan
    "tokyo": "JP",
    "osaka": "JP",
    "kyoto": "JP",
    "yokohama": "JP",
    "nagoya": "JP",
    # South Korea
    "seoul": "KR",
    "busan": "KR",
    # Brazil
    "são paulo": "BR",
    "sao paulo": "BR",
    "rio de janeiro": "BR",
    "brasília": "BR",
    "brasilia": "BR",
    "belo horizonte": "BR",
    # South Africa
    "johannesburg": "ZA",
    "cape town": "ZA",
    "durban": "ZA",
    "pretoria": "ZA",
    # Kenya
    "nairobi": "KE",
}


def country_code_for_city(name: str) -> str | None:
    """Look up an ISO 3166-1 alpha-2 country code for a city or country name.

    Backs the region setup skill's "add region" lookup so it doesn't maintain a
    second, smaller, drift-prone copy of this list in markdown.
    """
    return COUNTRY_NAME_TO_CODE.get(name.strip().lower())
